# World Portal Config file

# Permissions settings
permissions:
    usePermissions: true
    enableBypassPermissions: true
    permissionsSystems:
        PermissionsEx:
            enabled: true
        PermissionsBukkit:
            enabled: true
        bPermissions:
            enabled: true
        EssentialsGroupManager:
            enabled: true
        zPermissions:
            enabled: true
        Vault:
            enabled: true
        Permissions:
            enabled: true

# Economy settings
economy:
    useEconomy: true
    economySystems:
        SimpleEconomy:
            enabled: true
        BOSEconomy:
            enabled: true
        iConomy:
            enabled: true

# Tasks settings

# World Portal API settings

# Update checker

# Statistics
statistics:
    enabled: true

# Do never change the version number bellow, this is used to automatically update the configuration files
version: '0.3'