# In this config file you can change some settings for World Portal

# The world portals list file
WorldPortalsListFile: 'WorldPortals.list'

# Portals
WorldPortalProtection: true

# Show teleportation message (edit message in the message.yml file)
showMessageOnTeleportation: true

# Broadcast message on world generation and world loading (edit messages in the message.yml file)
broadcastMessageOnWorldGeneration: true
broadcastMessageOnWorldLoad: true

# Permissions settings
permissions:
    alwaysPermitOp: true
    usePermissions: true
    permissionsSystems:
        PermissionsEx:
            enabled: true
        PermissionsBukkit:
            enabled: true
        bPermissions:
            enabled: true
        GroupManager:
            enabled: true
        zPermissions:
            enabled: true
        Vault:
            enabled: true